---
name: "Tutorials"
guid: "0db4fc83-a755-4074-8c73-99425e43da24"
version: "1.0.0.0"
targetAbi: "1.0.0.0"
framework: "net5.0"
owner: "deriegle"
overview: "Manage your online courses and tutorials in Jellyfin"
description: >
  Manage your online courses and tutorials in Jellyfin. This plugin supports tutorials from all different sites and makes it easy to organize your collection of tutorials.
category: "Metadata"
artifacts:
- "Jellyfin.Plugin.Tutorials.dll"
changelog: >
  changelog
